### ISSUE TITLE
How do I use these snippets?

### ISSUE THREAD

**Issue by jdhines** [mattmcmanus/atom-ember-snippets#18]
In installed the package, both through `apm` and in-tool, restarted Atom twice, but still am not getting say the `eachelse` snippet to pop up in an `.hbs` file.

I've tried with the language set to HTMLBars and Ember HTMLBars.

**Comment by mattmcmanus** [comment]
@jdhines Wierd! Things seem to be working fine for me. Let me do some digging

**Comment by mattmcmanus** [comment]
@jdhines is it all of the snippets or just the handlebars ones?

**Comment by jdhines** [comment]
Seems to be just the handlebars ones

**Comment by mattmcmanus** [comment]
I just pushed `2.0.1` which may fix it. Let me know!

**Comment by jdhines** [comment]
What language do you have set? I upgraded and restarted Atom, but the template snippets still won't show up.

**Comment by mattmcmanus** [comment]
It was originally `.text.handlebars` and I updated it to `.text.html.handlebars`. Do you have the `atml-handlebars` package installed? When I open up an hbs file, the language type is set to `HTML (Handlebars)`

**Comment by jdhines** [comment]
I tried switching to HTML (Mustache), but I don't have a handlebars one. I installed the `language-ember-htmlbars` package

**Comment by mattmcmanus** [comment]
I'd definitely recommend `atom-handlebars` over `language-ember-htmlbars`. htmlbars in ember did not introduce any new language semantics that isn't already supported in the handlebars package. The only way this package can support both is to duplicate all the snippets with different sources or be less precise and risk having handlebars snippets being suggested in vanilla html.

**Comment by jdhines** [comment]
Switching to atom-handlebars solved the problem. Thank you.

**Comment by mattmcmanus** [comment]
@jdhines Sorry for the run around. I've had in the bottom of the readme "Recommend Packages" but clearly I didn't realize that the way I have things setup makes that package an explicit dependency. I'll see if I can declare it as such
